site:
  title: MicroProfile Tutorial
  url: https://microprofile.io
  start_path: ./
  name: microprofile-tutorial
  version: latest
  start_page: microprofile-tutorial::index.adoc

content:
  sources:
    - url: .
      start_path: .

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable

output:
  dir: ./build/site