site:
  title: MicroProfile Tutorial
  start_page: microprofile-tutorial::index.adoc

content:
  sources:
    - url: .
      start_path: .

ui:
  bundle:
    url: https://github.com/microprofile/microprofile-tutorial-ui/releases/tag/latest/ui-bundle.zip
output:
  dir: ./build/site

runtime:
  log:
    level: debug