name: Generate MicroProfile Tutorial

on:
  push:
    branches:
      - main  # Or your default branch

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use a compatible Node.js version

      - name: Install Antora Locally
        run: npm install @antora/cli @antora/site-generator-default
      
      - name: Verify Antora Installation
        run: npm list @antora/cli @antora/site-generator-default || echo "Antora packages are not installed."
      
      - name: Generate Site with Antora
        run: npx antora --fetch --stacktrace playbook.yml

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Antora Site to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/site  # The output directory for Antora