name: Generate MicroProfile Tutorial

on:
  push:
    branches:
      - main  # Or your default branch

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for authentication
      contents: read   # Required to read repository contents
      pages: write     # Required to deploy to GitHub Pages
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use a compatible Node.js version

      - name: Install Antora Locally
        run: npm install @antora/cli @antora/site-generator-default
      
      - name: Verify Antora Installation
        run: npm list @antora/cli @antora/site-generator-default || echo "Antora packages are not installed."
      
      - name: Generate Site with Antora
        run: npx antora --fetch --stacktrace playbook.yml

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with: 
          enablement: true

      - name: Upload Antora Site to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/site  # The output directory for Antora
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
